version: '3.8'

services:
  mysql:
    container_name: mysql-laravel-eloquent-spatial
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel_eloquent_spatial_test
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped
  postgres:
    container_name: postgres-laravel-eloquent-spatial
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: laravel_eloquent_spatial_test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: unless-stopped

volumes:
  mysql_data:
  postgres_data:
