name: Code quality analysis

on: [ push, pull_request ]

jobs:
  phpstan:
    name: PHPInsights

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPInsights
        run: ./vendor/bin/phpinsights --no-interaction --ansi --format=github-action

